spring:
  application:
    name: mic_eureka
server:
  port: 8180
  eureka_address: 127.0.0.1
eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.eureka_address}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info
  file: logs/${spring.application.name}.log