spring:
  application:
    name: mic_user
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: mic_user
      profile: dev
      fail-fast: true
server:
  port: 8181
  eureka_address: 127.0.0.1:8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.eureka_address}/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always