spring:
  application:
    name: mic_user
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: mic_user
      profile: dev
      fail-fast: true
  # 开发数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:  #初中综评93测试库
        driverClassName: oracle.jdbc.OracleDriver
        initial-size: 10
        max-active: 100
        min-idle: 20
        max-wait: 10000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 1800000
        validation-query: 'SELECT 1 FROM DUAL'
        validation-query-timeout: 10
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        use-unfair-lock: true
        remove-abandoned: true
        remove-abandoned-timeout: 1800
        url: jdbc:oracle:thin:@101.226.173.159:1521:zxxsybtest
        username: czzpuser
        password: czzpuser_159_!QAZ
      second:  #数据源2
        driverClassName: oracle.jdbc.OracleDriver
        initial-size: 10
        max-active: 100
        min-idle: 20
        max-wait: 10000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 1800000
        validation-query: 'SELECT 1 FROM DUAL'
        validation-query-timeout: 10
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        use-unfair-lock: true
        remove-abandoned: true
        remove-abandoned-timeout: 1800
        url: jdbc:oracle:thin:@101.226.173.159:1521:zxxsybtest
        username: czzpuser
        password: czzpuser_159_!QAZ
      third:  #数据源3
        driverClassName: oracle.jdbc.OracleDriver
        initial-size: 10
        max-active: 100
        min-idle: 20
        max-wait: 10000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 1800000
        validation-query: 'SELECT 1 FROM DUAL'
        validation-query-timeout: 10
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        use-unfair-lock: true
        remove-abandoned: true
        remove-abandoned-timeout: 1800
        url: jdbc:oracle:thin:@101.226.173.159:1521:zxxsybtest
        username: czzpuser
        password: czzpuser_159_!QAZ
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:
      stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
server:
  port: 8182
  eureka_address: 127.0.0.1:8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.eureka_address}/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
mybatis:
  type-aliases-package: com.cloud.commons.dao
  mapper-locations: classpath*:mybatis-mappers/*.xml
  configuration:
    mapUnderscoreToCamelCase: true