spring:
  application:
    name: mic_gateway
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: mic_gateway
      profile: dev
      fail-fast: true
server:
  port: 8181
  eureka_address: 127.0.0.1:8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.eureka_address}/eureka/
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000